%% Some predefined basis functions for linear model p_c

conductivities = [loCond upCond];
%generalized means
min_z = 1;
max_z = 1;
z_incr = .5;
z = min_z:z_incr:max_z;
i = 1;
for zz = z
    phi{i} = @(lambda) generalizedMean(lambda, zz);
    i = i + 1;
end
%log of generalized means
for zz = z
    phi{i} = @(lambda) log(generalizedMean(lambda, zz));
    i = i + 1;
end

dLinPathMax = 30;
dLinPathMin = 0;
dLinPathIncr = 1;
nElc = [domainc.nElX domainc.nElY];
nElf = [domainf.nElX domainf.nElY];
for d = dLinPathMin:dLinPathIncr:dLinPathMax
    phi{end + 1} = @(lambda) linealPath(lambda, d, 'x', 2, conductivities, nElc, nElf);
end
for d = dLinPathMin:dLinPathIncr:dLinPathMax
    phi{end + 1} = @(lambda) linealPath(lambda, d, 'y', 2, conductivities, nElc, nElf);
end

d2pointCorrMax = 30;
d2pointCorrMin = 2;
d2pointCorrIncr = 1;
for d = d2pointCorrMin:d2pointCorrIncr:d2pointCorrMax
    %distinct in x and y direction
    phi{end + 1} = @(lambda) twoPointCorrelation(lambda, d, 'x', 2, conductivities, nElc, nElf);
end
for d = d2pointCorrMin:d2pointCorrIncr:d2pointCorrMax
    %distinct in x and y direction
    phi{end + 1} = @(lambda) twoPointCorrelation(lambda, d, 'y', 2, conductivities, nElc, nElf);
end

pathLengths = (0:1:30)';
% lpa = @(lambda) linPathParams(lambda, pathLengths, conductivities, domainc, domainf, 'a');
lpb = @(lambda) abs(linPathParams(lambda, pathLengths, conductivities, domainc, domainf, 'b'));

mps = @(lambda) meanPoreSize(lambda, 2, conductivities, nElc, nElf, 'mean')/(nElf(1)/2);
vps = @(lambda) sqrt(meanPoreSize(lambda, 2, conductivities, nElc, nElf, 'var'))/(nElf(1)/2);

phi{end + 1} = mps;
phi{end + 1} = vps;
phi{end + 1} = @(lambda) specificSurface(lambda, 2, conductivities, nElc, nElf);
phi{end + 1} = lpb;
%This gives mean euclidean distance to nearest high conducting pixel
phi{end + 1} = @(lambda) mean(mean(bwdist(reshape(lambda > loCond, sqrt(length(lambda)), sqrt(length(lambda))))));
%This gives mean euclidean distance to nearest low conducting pixel
phi{end + 1} = @(lambda) mean(mean(bwdist(reshape(lambda < upCond, sqrt(length(lambda)), sqrt(length(lambda))))));
%Counts the number of separate high conducting blobs
phi{end + 1} = @(lambda) numberOfObjects(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))), conductivities, 'hi');
%Counts the number of separate low conducting blobs
phi{end + 1} = @(lambda) numberOfObjects(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))), conductivities, 'lo');

%% High conducting phase
%means
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Area', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'ConvexArea', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Eccentricity', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Extent', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'MajorAxisLength', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'MinorAxisLength', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Orientation', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Perimeter', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Solidity', 'mean');
%Variances
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Area', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'ConvexArea', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Eccentricity', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Extent', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'MajorAxisLength', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'MinorAxisLength', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Orientation', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Perimeter', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Solidity', 'var');
%Maxima
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Area', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'ConvexArea', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Eccentricity', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Extent', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'MajorAxisLength', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'MinorAxisLength', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Orientation', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Perimeter', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Solidity', 'max');
%Minima
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Area', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'ConvexArea', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Eccentricity', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Extent', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'MajorAxisLength', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'MinorAxisLength', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Orientation', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Perimeter', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Solidity', 'min');
%standard deviations
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Area', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'ConvexArea', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Eccentricity', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Extent', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'MajorAxisLength', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'MinorAxisLength', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Orientation', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Perimeter', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'Solidity', 'var').^.5;
%maximum bubble extents
phi{end + 1} = @(lambda) maxExtent(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'x');
phi{end + 1} = @(lambda) maxExtent(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'y');
%mean bubble extents
phi{end + 1} = @(lambda) meanExtent(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'x', 'mean');
phi{end + 1} = @(lambda) meanExtent(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'y', 'mean');
phi{end + 1} = @(lambda) meanExtent(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'x', 'var');
phi{end + 1} = @(lambda) meanExtent(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'hi', 'y', 'var');

%% Low conducting phase
%means
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Area', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'ConvexArea', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Eccentricity', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Extent', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'MajorAxisLength', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'MinorAxisLength', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Orientation', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Perimeter', 'mean');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Solidity', 'mean');
%Variances
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Area', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'ConvexArea', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Eccentricity', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Extent', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'MajorAxisLength', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'MinorAxisLength', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Orientation', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Perimeter', 'var');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Solidity', 'var');
%Maxima
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Area', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'ConvexArea', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Eccentricity', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Extent', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'MajorAxisLength', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'MinorAxisLength', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Orientation', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Perimeter', 'max');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Solidity', 'max');
%Minima
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Area', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'ConvexArea', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Eccentricity', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Extent', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'MajorAxisLength', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'MinorAxisLength', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Orientation', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Perimeter', 'min');
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Solidity', 'min');
%standard deviations
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Area', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'ConvexArea', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Eccentricity', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Extent', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'MajorAxisLength', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'MinorAxisLength', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Orientation', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Perimeter', 'var').^.5;
phi{end + 1} = @(lambda) meanImageProps(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'Solidity', 'var').^.5;
%maximum bubble extents
phi{end + 1} = @(lambda) maxExtent(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'x');
phi{end + 1} = @(lambda) maxExtent(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'y');
%mean bubble extents
phi{end + 1} = @(lambda) meanExtent(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'x', 'mean');
phi{end + 1} = @(lambda) meanExtent(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'y', 'mean');
phi{end + 1} = @(lambda) meanExtent(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'x', 'var');
phi{end + 1} = @(lambda) meanExtent(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))),...
    conductivities, 'lo', 'y', 'var');


%Energy of conductivity field if it were Ising model
phi{end + 1} = @(lambda) isingEnergy(reshape(lambda, sqrt(length(lambda)), sqrt(length(lambda))));
%constant
phi{end + 1} = @(lambda) 1;

%max/min
phi{end + 1} = @(lambda) max(lambda);
phi{end + 1} = @(lambda) min(lambda);


nBasis = numel(phi);


%print feature function strings to file
delete('./data/basisFunctions.txt');
fid = fopen('./data/basisFunctions.txt','wt');
for i = 1:length(phi)
    phi_str = func2str(phi{i});
    phi_str = strcat(phi_str, '\n');
    fprintf(fid, phi_str);
end
fclose(fid);



